### ISSUE TITLE
Fix handling of macroWeighted attribute

### ISSUE THREAD

**Issue by KseniaBastrakova** [ComputationalRadiationPhysics/particle_reduction#10]
According to OpenPMD-standard, all records in pic-extension should have [`macroWeighted` ](https://github.com/openPMD/openPMD-standard/blob/latest/EXT_ED-PIC.md#additional-attributes-for-each-particle-record)
parameter,which indicates whether this quantity is written for the underlying particle. The input in reduction algorithms has to be in particles, not in macroparticles. There is't conversion from macroparticle quantities  ` (macroWeighted = 1)` to particle quantities now, that's not correct

**Comment by sbastrakov** [comment]
PIConGPU seems to have a similar issue in its merging plugins. E.g. [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/834c06dd239263ca938bd6dac2abe75ef4986bf1/include/picongpu/plugins/particleMerging/VoronoiCell.hpp#L156-L157) the momentum is already weighted as input, and generally it seems the plugin should operate on non-weighted momentum instead, and there are mismatches of weighted vs. non-weighted.

**Comment by KseniaBastrakova** [comment]
> PIConGPU seems to have a similar issue in its merging plugins. E.g. [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/834c06dd239263ca938bd6dac2abe75ef4986bf1/include/picongpu/plugins/particleMerging/VoronoiCell.hpp#L156-L157) the momentum is already weighted as input, and generally it seems the plugin should operate on non-weighted momentum instead, and there are mismatches of weighted vs. non-weighted.

Yes, noticed that problem. I fix in my version of merging plugin, and it seems reasonable to fix this in the original plugin.
