### ISSUE TITLE
 Add library record names

### ISSUE THREAD

**Issue by KseniaBastrakova** [ComputationalRadiationPhysics/particle_reduction#11]
The opemPMD-standard has a few required Particle Records for particleSpices 
some of them are necessary for some merging algorithms, some are not. Now, the user's  particles Record are now supported correctly, so it's reasonable to add common mechanism for all types particle Records

**Comment by ax3l** [comment]
> The opemPMD-standard has a few required Particle Records for particleSpices

Just noting: you mean the `ED-PIC` extension of the openPMD-standard :+1: 

Thanks for the update!

**Comment by KseniaBastrakova** [comment]
@ax3l  yes, you are right, i told about extension
